server:
  port: 8081
  servlet:
    context-path: /activiti

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-activiti?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql


  activiti:
    check-process-definitions: false
    database-schema-update: true
    job-executor-activate: false
    jpa-enabled: true

  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    encoding: UTF-8
    enabled: true
    suffix: .html





